# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import mixed_sub_multiple.main_mod.mod_b

def greet_a(kind:mixed_sub_multiple.main_mod.mod_b.GreetingEnum) -> None: ...

