# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class A:
    def show_x(self) -> None: ...

@typing.final
class B:
    def show_x(self) -> None: ...

def create_a(x:builtins.int) -> A: ...

def create_b(x:builtins.int) -> B: ...

