# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing
__all__ = [
    "ClassA",
    "ClassB",
]

@typing.final
class ClassA:
    ...

@typing.final
class ClassB:
    def ClassA(self) -> ClassA: ...
    def collision(self, a: ClassA) -> ClassA: ...

