# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  stub-gen:
    desc: Generate stub file
    cmds:
      - cargo run --bin stub_gen

  test:
    desc: Run tests
    cmds:
      - uv run pytest
      - uv run pyright
      - uvx ruff check
      - uv run mypy --show-error-codes -p mixed.main_mod
      # stubtest is disabled for this example due to PyO3 nested submodule limitations
      # See README.md for details
      - uv run pyrefly check .
      - uv run ty check .

  doc-build:
    desc: Build Sphinx documentation
    deps:
      - stub-gen
    cmds:
      - uv run --with sphinx sphinx-build -W -b html docs docs/_build

  doc-test:
    desc: Test that Sphinx documentation builds and objects.inv exists
    deps:
      - doc-build
    cmds:
      - bash -c 'test -f docs/_build/index.html || (echo "ERROR index.html not generated" && exit 1)'
      - bash -c 'test -f docs/_build/objects.inv || (echo "ERROR objects.inv not generated" && exit 1)'
      - echo "✓ Documentation built successfully"
      - echo "✓ objects.inv generated for intersphinx"
