[package]
name = "pyo3-stub-gen-testing-mixed"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3-stub-gen = { path = "../pyo3-stub-gen" }
pyo3.workspace = true

[[bin]]
name = "stub_gen"
doc = false
