# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import numpy
import numpy.typing
import typing

def np_allow_type_change(x:typing.Union[numpy.typing.NDArray[typing.Any],numpy.typing.NDArray[numpy.float64],typing.Tuple[typing.Any, ...],typing.List[typing.Any],]) -> numpy.typing.NDArray[numpy.float64]: ...

def np_type_must_match(x:numpy.typing.NDArray[numpy.int16]) -> numpy.typing.NDArray[numpy.int16]: ...

