# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  stub-gen:
    desc: Generate stub file
    cmds:
      - cargo run --bin stub_gen

  test:
    desc: Run tests
    cmds:
      - uv run pytest
      # pyright is deliberately not executed here, as it is executed from the tests of this example
      - uvx ruff check
