# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "deep_function",
]

def deep_function() -> builtins.str:
    r"""
    A function in a deeply nested submodule.
    The module path must match the actual runtime structure:
    _native -> deep -> nested -> module
    """

