# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from . import deep
__all__ = [
    "NativeClass",
    "deep",
    "native_function",
]

@typing.final
class NativeClass:
    r"""
    A class defined in Rust that will be re-exported from __init__.py
    """
    @property
    def value(self) -> builtins.int: ...
    @value.setter
    def value(self, value: builtins.int) -> None: ...
    def __new__(cls, value: builtins.int) -> NativeClass: ...
    def double(self) -> builtins.int: ...

def native_function(x: builtins.int) -> builtins.int:
    r"""
    A function defined in Rust
    """

