# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pure:
    taskfile: examples/pure/Taskfile.yml
    dir: examples/pure
  mixed:
    taskfile: examples/mixed/Taskfile.yml
    dir: examples/mixed
  mixed_sub:
    taskfile: examples/mixed_sub/Taskfile.yml
    dir: examples/mixed_sub
  test-dash-package:
    taskfile: examples/test-dash-package/Taskfile.yml
    dir: examples/test-dash-package
  numpy_example:
    taskfile: examples/numpy_example/Taskfile.yml
    dir: examples/numpy_example

tasks:
  stub-gen:
    cmds:
      - task: pure:stub-gen
      - task: mixed:stub-gen
      - task: mixed_sub:stub-gen
      - task: test-dash-package:stub-gen
      - task: numpy_example:stub-gen

  test:
    cmds:
      - task: pure:test
      - task: mixed:test
      - task: mixed_sub:test
      - task: test-dash-package:test
      - task: numpy_example:test
