# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pure:
    taskfile: examples/pure/Taskfile.yml
    dir: examples/pure
  mixed:
    taskfile: examples/mixed/Taskfile.yml
    dir: examples/mixed
  test-dash-package:
    taskfile: examples/test-dash-package/Taskfile.yml
    dir: examples/test-dash-package
  feature_gated:
    taskfile: examples/feature_gated/Taskfile.yml
    dir: examples/feature_gated
  empty_super_module:
    taskfile: examples/empty_super_module/Taskfile.yml
    dir: examples/empty_super_module
  same_name_submod:
    taskfile: examples/same_name_submod/Taskfile.yml
    dir: examples/same_name_submod
  simple_name_collision:
    taskfile: examples/simple_name_collision/Taskfile.yml
    dir: examples/simple_name_collision
  avoid_name_collision_with_submod:
    taskfile: examples/avoid_name_collision_with_submod/Taskfile.yml
    dir: examples/avoid_name_collision_with_submod

tasks:
  stub-gen:
    cmds:
      - task: pure:stub-gen
      - task: mixed:stub-gen
      - task: test-dash-package:stub-gen
      - task: feature_gated:stub-gen
      - task: empty_super_module:stub-gen
      - task: same_name_submod:stub-gen
      - task: simple_name_collision:stub-gen
      - task: avoid_name_collision_with_submod:stub-gen

  test:
    cmds:
      - task: pure:test
      - task: mixed:test
      - task: test-dash-package:test
      - task: feature_gated:test
      - task: empty_super_module:test
      - task: same_name_submod:test
      - task: simple_name_collision:test
      - task: avoid_name_collision_with_submod:test
