# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pure:
    taskfile: examples/pure/Taskfile.yml
    dir: examples/pure
  mixed:
    taskfile: examples/mixed/Taskfile.yml
    dir: examples/mixed
  mixed_sub:
    taskfile: examples/mixed_sub/Taskfile.yml
    dir: examples/mixed_sub
  mixed_sub_multiple:
    taskfile: examples/mixed_sub_multiple/Taskfile.yml
    dir: examples/mixed_sub_multiple
  mixed_sub_import_type:
    taskfile: examples/mixed_sub_import_type/Taskfile.yml
    dir: examples/mixed_sub_import_type
  test-dash-package:
    taskfile: examples/test-dash-package/Taskfile.yml
    dir: examples/test-dash-package

tasks:
  stub-gen:
    cmds:
      - task: pure:stub-gen
      - task: mixed:stub-gen
      - task: mixed_sub:stub-gen
      - task: mixed_sub_import_type:stub-gen
      - task: mixed_sub_multiple:stub-gen
      - task: test-dash-package:stub-gen

  test:
    cmds:
      - task: pure:test
      - task: mixed:test
      - task: mixed_sub:test
      - task: mixed_sub_import_type:test
      - task: mixed_sub_multiple:test
      - task: test-dash-package:test
