# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pure:
    taskfile: examples/pure/Taskfile.yml
    dir: examples/pure
  mixed:
    taskfile: examples/mixed/Taskfile.yml
    dir: examples/mixed
  mixed_sub:
    taskfile: examples/mixed_sub/Taskfile.yml
    dir: examples/mixed_sub
  test-dash-package:
    taskfile: examples/test-dash-package/Taskfile.yml
    dir: examples/test-dash-package
  feature_gated:
    taskfile: examples/feature_gated/Taskfile.yml
    dir: examples/feature_gated
  empty_super_module:
    taskfile: examples/empty_super_module/Taskfile.yml
    dir: examples/empty_super_module

tasks:
  stub-gen:
    cmds:
      - task: pure:stub-gen
      - task: mixed:stub-gen
      - task: mixed_sub:stub-gen
      - task: test-dash-package:stub-gen
      - task: feature_gated:stub-gen
      - task: empty_super_module:stub-gen

  test:
    cmds:
      - task: pure:test
      - task: mixed:test
      - task: mixed_sub:test
      - task: test-dash-package:test
      - task: feature_gated:test
      - task: empty_super_module:test
