# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pure_abi3:
    taskfile: examples/pure_abi3/Taskfile.yml
    dir: examples/pure_abi3
  pure_unlimited:
    taskfile: examples/pure_unlimited/Taskfile.yml
    dir: examples/pure_unlimited
  mixed:
    taskfile: examples/mixed/Taskfile.yml
    dir: examples/mixed
  mixed_sub:
    taskfile: examples/mixed_sub/Taskfile.yml
    dir: examples/mixed_sub
  mixed_sub_multiple:
    taskfile: examples/mixed_sub_multiple/Taskfile.yml
    dir: examples/mixed_sub_multiple

tasks:
  stub-gen:
    cmds:
      - task: pure_abi3:stub-gen
      - task: pure_unlimited:stub-gen
      - task: mixed:stub-gen
      - task: mixed_sub:stub-gen
      - task: mixed_sub_multiple:stub-gen

  test:
    cmds:
      - task: pure_abi3:test
      - task: pure_unlimited:test
      - task: mixed:test
      - task: mixed_sub:test
      - task: mixed_sub_multiple:test
