# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
This is the main module docstring for hidden_module_docgen_test.
These lines are trimmed appropriately.

    This must be indented by four spaces.
"""

import builtins
from hidden_module_docgen_test._core import *
from . import _core
__all__ = [
    "A",
    "AorB",
    "B",
    "C",
    "ModAAlias",
    "create_a",
    "create_b",
    "default_c",
    "greet_main",
    "wrap_opt_a",
]

def create_b(x: builtins.int) -> _core.B:
    r"""
    This is the docstring fo {py:func}`great_main` function.
    
    These lines must be rendered as separate paragraphs.
    
    ```python
    >>> 42
    42
    ```
    
    This must be rendered: $x + x$
    """

