# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from hidden_module_docgen_test._core import *
from . import _core
__all__ = [
    "A",
    "B",
    "ModAAlias",
    "create_a",
    "create_b",
    "greet_main",
]

def create_b(x: builtins.int) -> _core.B: ...

