# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class D:
    def show_x(self) -> None: ...

def create_d(x: builtins.int) -> D: ...

def greet_b() -> None: ...

def test_submit_with_module(values: typing.List[int]) -> int:
    r"""
    Test function defined with gen_function_from_python! and module parameter
    """

