# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from . import _native
__all__ = [
    "DirectClass",
]

@typing.final
class DirectClass:
    r"""
    A class that is declared to belong directly to the top-level module.
    This simulates: #[pyclass(name = "A", module = "pkg")]
    The stub will be generated in pkg/__init__.pyi, not pkg/_native/__init__.pyi
    """
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    def __new__(cls, name: builtins.str) -> DirectClass: ...
    def greet(self) -> builtins.str: ...

