# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

from mixed import main_mod
import typing
from mixed.main_mod import B

@typing.final
class C:
    def show_x(self) -> None: ...

def create_c(a: main_mod.A, b: B) -> C: ...

def greet_a() -> None: ...

def test_module_with_python(x: typing.Generator[int, None, None]) -> int:
    r"""
    Test function with both module and python parameters
    """

