# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from mixed import main_mod
import typing
from typing import TypeAlias
__all__ = [
    "C",
    "ModAAlias",
    "create_c",
    "greet_a",
    "test_module_with_python",
]

ModAAlias: TypeAlias = builtins.int
@typing.final
class C:
    def show_x(self) -> None: ...

def create_c(a: main_mod.A, b: main_mod.B) -> C: ...

def greet_a() -> None: ...

def test_module_with_python(x: typing.Generator[int, None, None]) -> int:
    r"""
    Test function with both module and python parameters
    """

