version: '3'

tasks:
  stub-gen:
    cmds:
      - cargo run --bin stub_gen
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - python/**/*.pyi

  test:
    deps: [stub-gen]
    cmds:
      - uv run pyright
      - uvx ruff check
      # The following two cases should pass, as types are fully qualified to avoid namespace collision.
      - uv run pyrefly check -c ./pyproject.toml .
      - uv run ty check .
