# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import enum
import typing

@typing.final
class OnlyPyo3Module:
    r"""
    Test 2: Only pyo3 module → uses pyo3 module
    """
    ...

@typing.final
class OnlyPyo3Enum(enum.Enum):
    r"""
    Test 1: Only pyo3 module
    """
    A = ...
    B = ...

