# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing
from avoid_name_collision_with_submod.sub_mod import ClassA
from . import sub_mod

@typing.final
class ClassB:
    def ClassA(self) -> ClassA: ...
    def collision(self, a: ClassA) -> ClassA: ...

