# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  stub-gen:
    desc: Generate stub file
    cmds:
      - cargo run --bin stub_gen

  test:
    desc: Run tests
    cmds:
      - uv run pytest
      - uv run pyright
      - uvx ruff check
      - uv run --group dev mypy --show-error-codes test_dash_package.pyi
      - uv run --group dev python -m mypy.stubtest test_dash_package --ignore-missing-stub
