# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import enum
import typing
__all__ = [
    "InlineOverridesPyo3Class",
    "InlineOverridesPyo3Enum",
    "OnlyInlineClass",
    "OnlyInlineEnum",
    "only_inline_fn",
]

@typing.final
class InlineOverridesPyo3Class:
    r"""
    Test 3: Inline parameter overrides pyo3
    """
    ...

@typing.final
class OnlyInlineClass:
    r"""
    Test 4: Only inline (no pyo3)
    """
    ...

@typing.final
class InlineOverridesPyo3Enum(enum.Enum):
    r"""
    Test 2: Inline overrides pyo3
    """
    A = ...
    B = ...

@typing.final
class OnlyInlineEnum(enum.Enum):
    r"""
    Test 3: Only inline (no pyo3)
    """
    A = ...
    B = ...

def only_inline_fn() -> builtins.int:
    r"""
    Test 2: Only inline module
    """

