[package]
name = "pyo3-stub-gen-testing-pure"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3-stub-gen = { path = "../pyo3-stub-gen" }
pyo3.workspace = true

[[bin]]
name = "stub_gen"
doc = false
