# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

def sum(v:typing.Sequence[int]) -> int:
    r"""
    Returns the sum of two numbers as a string.
    """
    ...

class MyError(RuntimeError): ...

