# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

from typing import final, Any, List, Dict, Sequence, Mapping
from enum import Enum, auto

def sum_as_string(a:int,b:int) -> str:
    r"""
    Returns the sum of two numbers as a string.
    """
    ...

