version: '3'

tasks:
  stub-gen:
    cmds:
      - cargo run --bin stub_gen
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - python/**/*.pyi

  test:
    cmds:
      - task: stub-gen
      - uv run pyright
      - uvx ruff check
