version: '3'

tasks:
  stub-gen:
    cmds:
      - cargo run --bin stub_gen
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - python/**/*.pyi

  test:
    deps: [stub-gen]
    cmds:
      - uv run pytest
      - uv run pyright
      - uvx ruff check