version: '3'

tasks:
  build:
    cmds:
      - uv sync
    sources:
      - src/**/*.rs
      - Cargo.toml
      - pyproject.toml

  stub-gen:
    deps: [build]
    cmds:
      - cargo run --bin stub_gen
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - python/**/*.pyi

  test:
    deps: [stub-gen]
    cmds:
      - uv run pytest
      - uv run pyright
      - uvx ruff check
      - uv run pyrefly check -c ./pyproject.toml .
      - uv run ty check .