# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: CPY001, D200, D212, E501, F401

import builtins
from . import int
from . import sub_mod

class A:
    def show_x(self) -> None:
        ...


class B:
    def show_x(self) -> None:
        ...


def create_a(x:builtins.int) -> A:
    ...

def create_b(x:builtins.int) -> B:
    ...

