# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing
from mixed_sub.main_mod import A, B

@typing.final
class C:
    def show_x(self) -> None: ...

def create_c(a: A, b: B) -> C: ...

def greet_a() -> None: ...

def test_module_with_python(x: typing.Generator[int, None, None]) -> int:
    r"""
    Test function with both module and python parameters
    """

