# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class D:
    def show_x(self) -> None: ...

def create_d(x:builtins.int) -> D: ...

def greet_b() -> None: ...

