# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

from mixed_sub.main_mod import A, B

class C:
    def show_x(self) -> None: ...

def create_c(a:A, b:B) -> C: ...

def greet_a() -> None: ...

