# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from typing import TypeAlias
__all__ = [
    "A",
    "B",
    "ModAAlias",
    "create_a",
    "greet_main",
]

ModAAlias: TypeAlias = A
@typing.final
class A:
    def show_x(self) -> None: ...

@typing.final
class B:
    def show_x(self) -> None: ...

def create_a(x: builtins.int) -> A: ...

def greet_main() -> None:
    r"""
    This is the docstring fo {py:func}`great_main` function.
    
    These lines must be rendered as separate paragraphs.
    
    ```python
    >>> 42
    42
    ```
    
    Another math test \(\int_{-\infty}^\infty e^{-x^2} \mathrm{d}x\).
    """

