# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import typing
__all__ = [
    "CallbackType",
    "ComplexNested",
    "DocumentedModernAlias",
    "DocumentedTypeStatement",
    "GenericUnion",
    "MultiLineDocTypeStatement",
    "NumberOrString",
    "OptionalCallback",
    "SimpleAlias",
    "StrIntMap",
    "TripleUnion",
    "UndocumentedModernAlias",
    "UndocumentedTypeStatement",
]

type CallbackType = collections.abc.Callable[[str], None]
type ComplexNested = typing.Optional[builtins.dict[builtins.str, builtins.list[builtins.int]]]
type DocumentedModernAlias = builtins.int | builtins.str
r"""
A modern type alias with documentation
"""

type DocumentedTypeStatement = int | str
r"""
A type statement with documentation
"""

type GenericUnion = typing.Optional[builtins.int] | builtins.list[builtins.str]
type MultiLineDocTypeStatement = dict[str, int]
r"""
A type statement with multi-line documentation.

This is useful for complex types that need detailed explanation.
"""

type NumberOrString = builtins.int | builtins.str
type OptionalCallback = collections.abc.Callable[[str], None] | None
type SimpleAlias = typing.Optional[builtins.int]
type StrIntMap = builtins.dict[builtins.str, builtins.int]
type TripleUnion = builtins.int | builtins.str | builtins.bool
type UndocumentedModernAlias = builtins.list[builtins.str]
type UndocumentedTypeStatement = list[str]
