# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import typing
__all__ = [
    "CallbackType",
    "ComplexNested",
    "GenericUnion",
    "NumberOrString",
    "OptionalCallback",
    "SimpleAlias",
    "StrIntMap",
    "TripleUnion",
]

type CallbackType = collections.abc.Callable[[str], None]
type ComplexNested = typing.Optional[builtins.dict[builtins.str, builtins.list[builtins.int]]]
type GenericUnion = typing.Optional[builtins.int] | builtins.list[builtins.str]
type NumberOrString = builtins.int | builtins.str
type OptionalCallback = collections.abc.Callable[[str], None] | None
type SimpleAlias = typing.Optional[builtins.int]
type StrIntMap = builtins.dict[builtins.str, builtins.int]
type TripleUnion = builtins.int | builtins.str | builtins.bool
