# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  doc:
    taskfile: ../doc.yml
    flatten: true
    dir: .

tasks:
  stub-gen:
    desc: Generate stub file
    cmds:
      - cargo run --bin stub_gen

  test:
    desc: Run tests
    cmds:
      - uv run --locked --project ../.. pytest
      - uv run --locked --project ../.. pyright
      - uv run --locked --project ../.. ruff check
      - uv run --locked --project ../.. mypy --show-error-codes -p pure
      - uv run --locked --project ../.. stubtest pure --ignore-missing-stub --ignore-disjoint-bases --allowlist .stubtest-allowlist
      - uv run --locked --project ../.. pyrefly check ./pure.pyi
      - uv run --locked --project ../.. ty check .
