# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
from typing import TypeAlias
__all__ = [
    "A",
    "AorB",
    "B",
    "C",
    "create_a",
    "create_b",
    "default_c",
    "greet_main",
    "wrap_opt_a",
]

AorB: TypeAlias = A  |  B
@typing.final
class A:
    def show_x(self) -> None: ...

@typing.final
class B:
    def show_x(self) -> None: ...

@typing.final
class C(enum.Enum):
    r"""
    This is the docstring for enum C.
    """
    C0 = ...
    r"""
    This is 0th variant
    """
    C1 = ...
    r"""
    This is 1st variant
    """
    C2 = ...
    r"""
    This is 2nd variant
    """

def create_a(x: builtins.int) -> A: ...

def create_b(x: builtins.int) -> B:
    r"""
    This is the docstring for {py:func}`great_main` function.
    
    These lines must be rendered as separate paragraphs.
    
    ```python
    >>> 42
    42
    ```
    
    This must be rendered: $x + x$
    """

def default_c(c: C = C.C1) -> C:
    r"""
    A function with a default argument
    """

def greet_main() -> None:
    r"""
    This is the docstring fo {py:func}`great_main` function.
    
    These lines must be rendered as separate paragraphs.
    
    ```python
    >>> 42
    42
    ```
    
    Another math test $\int_{-\infty}^\infty e^{-x^2} \mathrm{d}x$.
    """

def wrap_opt_a(x: typing.Optional[A]) -> typing.Optional[A]: ...

