# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
from same_name_submod.pkg_a import sub_mod
from same_name_submod.pkg_b import sub_mod

def use_both(a: sub_mod.ClassA, b: sub_mod.ClassB) -> builtins.int: ...

