# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing
__all__ = [
    "HiddenClass",
    "hidden_function",
]

@typing.final
class HiddenClass:
    ...

def hidden_function() -> None: ...

