# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
This is the main module docstring for generate_init_py.
This example demonstrates the generate-init-py feature.

    This must be indented by four spaces.
"""

from generate_init_py._core import A, AorB, B, C, ModAAlias, create_a, create_b, default_c, greet_main, wrap_opt_a
__all__ = [
    "A",
    "AorB",
    "B",
    "C",
    "ModAAlias",
    "create_a",
    "create_b",
    "default_c",
    "greet_main",
    "wrap_opt_a",
]

