# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: F401
"""
This is the main module docstring for generate_init_py.
This example demonstrates the generate-init-py feature.

    This must be indented by four spaces.

Literal Python strings:

    text = \"\"\"A triple-quoted string\"\"\"
    path = r\"C:\\new\\tools\"
    pattern = r\"\\d+\\s\"
    continued = \\
        \"next line\"
"""

from generate_init_py._core import A, AorB, B, C, create_a, create_b, default_c, greet_main, wrap_opt_a
__all__ = [
    "A",
    "AorB",
    "B",
    "C",
    "create_a",
    "create_b",
    "default_c",
    "greet_main",
    "wrap_opt_a",
]
