"""A pure Python submodule with SomeClass.

This class is re-exported from the parent __init__.py,
but this re-export will be invisible to type checkers
when __init__.pyi is generated by pyo3-stub-gen.
"""


class SomeClass:
    """A pure Python class that should be re-exported from the parent module."""

    def __init__(self, name: str) -> None:
        self.name = name

    def greet(self) -> str:
        return f"Hello, {self.name}!"


def some_function(x: int) -> int:
    """A pure Python function."""
    return x * 2
