# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import enum
import typing

@typing.final
class PyClassA(enum.Enum):
    Option1 = ...
    Option2 = ...

    def my_elements(self) -> builtins.list[sub_mod.PyClassA]: ...

