# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import enum
import typing

@typing.final
class ClassA(enum.Enum):
    Option1 = ...
    Option2 = ...

    def bitor_type_info(self) -> sub_mod.ClassA | type: ...
    def my_elements(self) -> builtins.list[ClassA]: ...
