# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "ClassA",
]

@typing.final
class ClassA(enum.Enum):
    Option1 = ...
    Option2 = ...

    def bitor_type_info(self) -> ClassA  |  type: ...
    def my_elements(self) -> builtins.list[ClassA]: ...

