# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class A:
    def show_x(self) -> None:
        ...


class B:
    def show_x(self) -> None:
        ...


def create_a(x:int) -> A:
    ...

def create_b(x:int) -> B:
    ...

