# This file is automatically generated by pyo3_stub_gen

from typing import final, Any, List, Dict
from enum import Enum, auto

def sum_as_string(a,b) -> str:
    r"""
    Returns the sum of two numbers as a string.
    """
    ...

