# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from mixed.main_mod.mod_a import *
from mixed.main_mod.mod_b import D, greet_b
from . import int
from . import mod_a
from . import mod_b
__all__ = [
    "A",
    "B",
    "C",
    "D",
    "NoModuleAttr",
    "create_a",
    "create_b",
    "create_c",
    "greet_a",
    "greet_b",
    "greet_main",
    "int",
    "mod_a",
    "mod_b",
    "no_module_fn",
    "test_module_with_python",
]

@typing.final
class A:
    def show_x(self) -> None: ...

@typing.final
class B:
    def show_x(self) -> None: ...

@typing.final
class NoModuleAttr:
    r"""
    Test 1: No module attribute → uses default
    """
    ...

def create_a(x: builtins.int) -> 'A': ...

def create_b(x: builtins.int) -> 'B': ...

def greet_main() -> None: ...

def no_module_fn() -> builtins.int:
    r"""
    Test 1: No module → uses default
    """

