# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  stub-gen:
    desc: Generate stub file
    cmds:
      - cargo run --bin stub_gen

  test:
    desc: Run tests
    cmds:
      - uv run pytest
      - uv run pyright
      - uvx ruff check
      - uv run --group dev mypy --show-error-codes python/mixed_sub/main_mod/__init__.pyi python/mixed_sub/main_mod/int.pyi python/mixed_sub/main_mod/mod_a.pyi python/mixed_sub/main_mod/mod_b.pyi
      - uv run --group dev python -m mypy.stubtest mixed_sub.main_mod --ignore-missing-stub
