# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "A",
    "sum_as_string",
]

@typing.final
class A:
    @property
    def x(self) -> builtins.int:
        r"""
        ```python
        default = 0
        ```
        """
    @x.setter
    def x(self, value: builtins.int) -> None:
        r"""
        ```python
        default = 0
        ```
        """
    def __new__(cls) -> 'A': ...
    def get_y(self) -> builtins.int: ...

def sum_as_string(a: builtins.int, b: builtins.int) -> builtins.str:
    r"""
    Formats the sum of two numbers as string.
    """

