# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  stub-gen:
    desc: Generate stub file
    cmds:
      - cargo run --bin stub_gen --features="stub-gen"

  test:
    desc: Run tests
    cmds:
      - uv run --locked --project ../.. pytest
      - uv run --locked --project ../.. pyright
      - uv run --locked --project ../.. ruff check
      - uv run --locked --project ../.. mypy --show-error-codes -p feature_gated
      - uv run --locked --project ../.. stubtest feature_gated --ignore-missing-stub --ignore-disjoint-bases
      - uv run --locked --project ../.. pyrefly check .
      - uv run --locked --project ../.. ty check .
