# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  stub-gen:
    desc: Generate stub file
    cmds:
      - cargo run --bin stub_gen --features="stub-gen"

  test:
    desc: Run tests
    cmds:
      - uv run pytest
      - uv run pyright
      - uvx ruff check
      - uv run mypy --show-error-codes -p feature_gated
      - uv run stubtest feature_gated --ignore-missing-stub --ignore-disjoint-bases
